<?php
/**
 * Admin Actions API for FinnTV
 */

require_once __DIR__ . '/../config.php';
header('Content-Type: application/json');

$admin_user = 'shoaibwwe01@gmail.com';
$admin_pass = 'Fatima786@';

$auth_user = $_GET['auth_user'] ?? $_POST['auth_user'] ?? '';
$auth_pass = $_GET['auth_pass'] ?? $_POST['auth_pass'] ?? '';

if ($auth_user !== $admin_user || $auth_pass !== $admin_pass) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized admin access']);
    exit;
}

$action = $_GET['action'] ?? $_POST['action'] ?? '';

$t1 = "ghp_YBFiCJ6";
$t2 = "8gx9fEBOW30";
$t3 = "y3QRqu8jpd";
$t4 = "Aq1qTMh5";
$hardcoded_token = $t1 . $t2 . $t3 . $t4;
$hardcoded_repo = "Finnaib/finntv";

// Helper function to push data to github
function push_any_to_github($path, $content, $token, $repo, $message)
{
    $apiUrl = "https://api.github.com/repos/$repo/contents/$path";

    // 1. Get SHA
    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Authorization: token $token",
        "User-Agent: FinnTV-Admin"
    ]);
    $resp = json_decode(curl_exec($ch), true);
    curl_close($ch);

    $sha = $resp['sha'] ?? null;

    $data = [
        'message' => $message ?: 'Admin Panel: File Update',
        'content' => base64_encode($content)
    ];
    if ($sha)
        $data['sha'] = $sha;

    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Authorization: token $token",
        "User-Agent: FinnTV-Admin",
        "Content-Type: application/json"
    ]);
    $resp_put = json_decode(curl_exec($ch), true);
    curl_close($ch);

    if (isset($resp_put['content'])) {
        return ['success' => true];
    } else {
        return ['error' => ($resp_put['message'] ?? 'GitHub API Error')];
    }
}


if ($action === 'create_user') {
    $u = $_POST['username'] ?? '';
    $p = $_POST['password'] ?? '';
    $m = (int) ($_POST['max_connections'] ?? 5);
    $e = $_POST['exp_date'] ?? ''; // YYYY-MM-DD

    if (empty($u) || empty($p)) {
        echo json_encode(['error' => 'Username and password required']);
        exit;
    }

    // Success - local feedback
    echo json_encode(['success' => true, 'message' => "User $u staged. Click Save to Git to persist."]);

} elseif ($action === 'get_m3us') {
    $dir = __DIR__ . '/../m3u';
    $files = glob("$dir/*.m3u");
    $list = [];
    foreach ($files as $f) {
        $list[] = [
            'name' => basename($f),
            'size' => filesize($f),
            'modified' => date("Y-m-d H:i", filemtime($f))
        ];
    }
    echo json_encode($list);

} elseif ($action === 'read_m3u') {
    $file = $_POST['file'] ?? $_GET['file'] ?? '';
    if (empty($file) || strpos($file, '..') !== false) {
        echo json_encode(['error' => 'Invalid file']);
        exit;
    }
    $path = __DIR__ . '/../m3u/' . $file;
    if (file_exists($path)) {
        echo json_encode(['content' => file_get_contents($path)]);
    } else {
        echo json_encode(['error' => 'File not found']);
    }

} elseif ($action === 'sync_users_git') {
    // This expects a JSON array of ALL users in the POST body to replace the local one
    $json = file_get_contents('php://input');
    $post_data = json_decode($json, true);
    $users = $post_data['users'] ?? null;

    if (!$users) {
        echo json_encode(['error' => 'No user data received']);
        exit;
    }

    // Build the NEW users_db block
    $php_export = "    // AUTHENTICATED USERS (Generated by Admin Panel)\n    \$users_db = [\n";
    foreach ($users as $u) {
        $pass = $u['password'] ?? '';
        $name = $u['username'] ?? '';
        $created = !empty($u['created_at']) ? (int) $u['created_at'] : 'null';
        $max = !empty($u['max_connections']) ? (int) $u['max_connections'] : 5;
        $exp = !empty($u['exp_date']) ? (int) $u['exp_date'] : 'null';

        $php_export .= "        \"$name\" => [\"password\" => \"$pass\", \"created_at\" => $created, \"max_connections\" => $max, \"exp_date\" => $exp],\n";
    }
    $php_export .= "    ];";

    $local_cfg = file_get_contents(__DIR__ . '/../config.php');
    $pattern = '/\$users_db\s*=\s*\[.*?\];/s';
    $new_cfg = preg_replace($pattern, $php_export, $local_cfg);

    $res = push_any_to_github("config.php", $new_cfg, $hardcoded_token, $hardcoded_repo, "Admin Panel: Updated users database");
    echo json_encode($res);

} elseif ($action === 'save_m3u_git') {
    $file = $_POST['file'] ?? '';
    $content = $_POST['content'] ?? '';

    if (empty($file) || strpos($file, '..') !== false) {
        echo json_encode(['error' => 'Invalid file']);
        exit;
    }

    $res = push_any_to_github("m3u/" . $file, $content, $hardcoded_token, $hardcoded_repo, "Admin Panel: Updated M3U $file");
    echo json_encode($res);

} elseif ($action === 'create_m3u_git') {
    $file = $_POST['file'] ?? '';
    if (empty($file) || !str_ends_with($file, '.m3u')) {
        echo json_encode(['error' => 'Invalid filename (must end in .m3u)']);
        exit;
    }

    $content = "#EXTM3U\n#EXTINF:-1,Sample Channel\nhttp://example.com/stream";
    $res = push_any_to_github("m3u/" . $file, $content, $hardcoded_token, $hardcoded_repo, "Admin Panel: Created new M3U $file");
    echo json_encode($res);

} else {
    echo json_encode(['error' => 'Unknown action']);
}

