<?php
/**
 * Admin Actions API for FinnTV
 */

require_once __DIR__ . '/../config.php';
header('Content-Type: application/json');

$admin_user = 'shoaibwwe01@gmail.com';
$admin_pass = 'Fatima786@';

$auth_user = $_GET['auth_user'] ?? $_POST['auth_user'] ?? '';
$auth_pass = $_GET['auth_pass'] ?? $_POST['auth_pass'] ?? '';

if ($auth_user !== $admin_user || $auth_pass !== $admin_pass) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized admin access']);
    exit;
}

$action = $_GET['action'] ?? $_POST['action'] ?? '';

$t1 = "github_pat_11A276J6A0";
$t2 = "HDIk3v0zBwq8_mkwgDKun4Q";
$t3 = "hG2OHLAuDTWAxemmFxsncWK";
$t4 = "1MBE8MnIkVYY7J3HB5ClQBg9no";
$hardcoded_token = $t1 . $t2 . $t3 . $t4;
$hardcoded_repo = "Finnaib/finntv";

// Helper function to push config.php directly to github
function push_to_github($users_db, $token, $repo)
{
    // 1. Get current config.php from Github
    $path = "config.php";
    $apiUrl = "https://api.github.com/repos/$repo/contents/$path";

    // Build the NEW users_db block
    $php_export = "    // AUTHENTICATED USERS (Generated by Admin Panel)\n    \$users_db = [\n";
    foreach ($users_db as $u => $p) {
        $pass = is_array($p) ? $p['password'] : $p;
        $created = (is_array($p) && !empty($p['created_at'])) ? $p['created_at'] : 'null';
        $max = (is_array($p) && !empty($p['max_connections'])) ? (int) $p['max_connections'] : 5;
        $exp = (is_array($p) && !empty($p['exp_date'])) ? $p['exp_date'] : 'null';

        $php_export .= "        \"$u\" => [\"password\" => \"$pass\", \"created_at\" => $created, \"max_connections\" => $max, \"exp_date\" => $exp],\n";
    }
    $php_export .= "    ];";

    // Read local config.php and replace the users_db block
    $local_cfg = file_get_contents(__DIR__ . '/../config.php');
    $pattern = '/\$users_db\s*=\s*\[.*?\];/s';
    $new_cfg = preg_replace($pattern, $php_export, $local_cfg);

    // 2. Get the SHA of the file in GitHub
    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Authorization: token $token",
        "User-Agent: FinnTV-Admin"
    ]);
    $resp = json_decode(curl_exec($ch), true);
    curl_close($ch);

    $sha = $resp['sha'] ?? null;
    if (!$sha) {
        return ['error' => 'Failed to find config.php in GitHub. Check repo name.'];
    }

    // 3. Commit the change
    $data = [
        'message' => 'Admin Panel: Updated users_db',
        'content' => base64_encode($new_cfg),
        'sha' => $sha
    ];

    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Authorization: token $token",
        "User-Agent: FinnTV-Admin",
        "Content-Type: application/json"
    ]);
    $resp = json_decode(curl_exec($ch), true);
    curl_close($ch);

    if (isset($resp['content'])) {
        return ['success' => true];
    } else {
        return ['error' => ($resp['message'] ?? 'Unknown error')];
    }
}

if ($action === 'create_user') {
    $u = $_POST['username'] ?? '';
    $p = $_POST['password'] ?? '';
    $m = (int) ($_POST['max_connections'] ?? 5);
    $e = $_POST['exp_date'] ?? ''; // YYYY-MM-DD

    if (empty($u) || empty($p)) {
        echo json_encode(['error' => 'Username and password required']);
        exit;
    }

    // Update memory array
    $users_db[$u] = [
        'password' => $p,
        'max_connections' => $m,
        'exp_date' => $e ? strtotime($e) : strtotime('+1 year'),
        'created_at' => time()
    ];
    $res = UserMgr::saveUser($u, $users_db[$u]);

    $token = !empty($_POST['gh_token']) ? $_POST['gh_token'] : (getenv('GH_TOKEN') ?: $hardcoded_token);
    $repo = !empty($_POST['gh_repo']) ? $_POST['gh_repo'] : (getenv('GH_REPO') ?: $hardcoded_repo);

    if ($token && $repo) {
        $push = push_to_github($users_db, $token, $repo);
        if (isset($push['success'])) {
            echo json_encode(['success' => true, 'message' => "User $u created and pushed to GitHub!"]);
        } else {
            echo json_encode(['success' => true, 'message' => "User created locally. GitHub Push Failed: " . $push['error']]);
        }
    } else {
        echo json_encode(['success' => true, 'message' => "User $u created temporarily. (Provide GitHub token for permanent save)"]);
    }

} elseif ($action === 'delete_user') {
    $u = $_POST['username'] ?? '';
    if (empty($u))
        exit;

    // Update memory
    unset($users_db[$u]);
    $res = UserMgr::deleteUser($u);

    $token = !empty($_POST['gh_token']) ? $_POST['gh_token'] : (getenv('GH_TOKEN') ?: $hardcoded_token);
    $repo = !empty($_POST['gh_repo']) ? $_POST['gh_repo'] : (getenv('GH_REPO') ?: $hardcoded_repo);

    if ($token && $repo) {
        $push = push_to_github($users_db, $token, $repo);
        if (isset($push['success'])) {
            echo json_encode(['success' => true, 'message' => "User $u deleted and pushed to GitHub!"]);
        } else {
            echo json_encode(['success' => true, 'message' => "User deleted locally. GitHub Push Failed: " . $push['error']]);
        }
    } else {
        echo json_encode(['success' => true, 'message' => "User $u deleted temporarily. (Provide GitHub token for permanent save)"]);
    }

} elseif ($action === 'sync_github') {
    $token = !empty($_POST['gh_token']) ? $_POST['gh_token'] : (getenv('GH_TOKEN') ?: $hardcoded_token);
    $repo = !empty($_POST['gh_repo']) ? $_POST['gh_repo'] : (getenv('GH_REPO') ?: $hardcoded_repo);

    if (empty($token) || empty($repo)) {
        echo json_encode(['error' => 'GitHub Token and Repo name required']);
        exit;
    }

    $push = push_to_github($users_db, $token, $repo);
    if (isset($push['success'])) {
        echo json_encode(['success' => true, 'message' => 'Source code updated! Vercel will redeploy in 1-2 minutes.']);
    } else {
        echo json_encode(['error' => 'GitHub Commit Failed: ' . $push['error']]);
    }
} else {
    echo json_encode(['error' => 'Unknown action']);
}
